/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

import controller.*;
/**
 *
 * @author lenovo
 */
public class AdminPage extends javax.swing.JPanel {
//    MainFrame mf = new MainFrame();
//    flowControl fc = new flowControl();
//    LoginPage lp = new LoginPage();
    /**
     * Creates new form LoginPage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomLabel = new javax.swing.JLabel();
        createBookingButton = new javax.swing.JButton();
        createGuestButton = new javax.swing.JButton();
        viewBookingsButton = new javax.swing.JButton();

        WelcomLabel.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        WelcomLabel.setText("Welcome Back");

        createBookingButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createBookingButton.setText("Create New Booking");
        createBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBookingButtonActionPerformed(evt);
            }
        });

        createGuestButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createGuestButton.setText("Create New Guest");
        createGuestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGuestButtonActionPerformed(evt);
            }
        });

        viewBookingsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewBookingsButton.setText("View Bookings");
        viewBookingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBookingsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(WelcomLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(createBookingButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createGuestButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(viewBookingsButton)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(WelcomLabel)
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBookingButton)
                    .addComponent(createGuestButton)
                    .addComponent(viewBookingsButton))
                .addContainerGap(384, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBookingButtonActionPerformed
        // TODO add your handling code here:
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
                JPanel panel = new CreateBooking();
                currentFrame.dispose();
                JFrame frame = new JFrame("Create Booking");
                frame.add(panel);
                frame.setSize(750,600);
                frame.setVisible(true);
    }//GEN-LAST:event_createBookingButtonActionPerformed

    private void createGuestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGuestButtonActionPerformed
        // TODO add your handling code here:
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
                JPanel panel = new CreateProfile();
                currentFrame.dispose();
                JFrame frame = new JFrame("Create Profile");
                frame.add(panel);
                frame.setSize(750,600);
                frame.setVisible(true);
    }//GEN-LAST:event_createGuestButtonActionPerformed

    private void viewBookingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBookingsButtonActionPerformed
        // TODO add your handling code here:
//        lp.fc.grantAccess();
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        MainFrame mfO = new MainFrame();
//        lp.fc.grantAccess();
        JFrame frame = mfO;
//        MainFrame mf = (mfO) frame;
        currentFrame.dispose();
        
//                JFrame frame = new JFrame("Create Booking");
//                frame.add(panel);
        frame.setSize(750,600);
        frame.setVisible(true);
        
    }//GEN-LAST:event_viewBookingsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WelcomLabel;
    private javax.swing.JButton createBookingButton;
    private javax.swing.JButton createGuestButton;
    private javax.swing.JButton viewBookingsButton;
    // End of variables declaration//GEN-END:variables
}
