/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import model.*;


/**
 *
 * @author lenovo
 */
public class CreateProfile extends javax.swing.JPanel {

    /**
     * Creates new form CreateProfile
     */
    public CreateProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        FNameLabel = new javax.swing.JLabel();
        LNameLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        AL1Label = new javax.swing.JLabel();
        AL2Label = new javax.swing.JLabel();
        StateLabel = new javax.swing.JLabel();
        CityLabel = new javax.swing.JLabel();
        FNameInput = new javax.swing.JTextField();
        EmailInput = new javax.swing.JTextField();
        LNameInput = new javax.swing.JTextField();
        PhoneInput = new javax.swing.JTextField();
        AL1Input = new javax.swing.JTextField();
        AL2Input = new javax.swing.JTextField();
        StateInput = new javax.swing.JTextField();
        CityInput = new javax.swing.JTextField();
        CreateButton = new javax.swing.JButton();

        headingLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        headingLabel.setText("Create New Profile");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        FNameLabel.setText("First Name:");

        LNameLabel.setText("Last Name:");

        EmailLabel.setText("Email:");

        PhoneLabel.setText("Phone:");

        AL1Label.setText("Address Line 1:");

        AL2Label.setText("Address Line 2:");

        StateLabel.setText("State:");

        CityLabel.setText("City:");

        FNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameInputActionPerformed(evt);
            }
        });

        CreateButton.setText("Create Profile");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(headingLabel)
                .addGap(204, 204, 204)
                .addComponent(cancelButton)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FNameLabel)
                            .addComponent(LNameLabel)
                            .addComponent(EmailLabel)
                            .addComponent(PhoneLabel)
                            .addComponent(AL1Label)
                            .addComponent(AL2Label)
                            .addComponent(StateLabel)
                            .addComponent(CityLabel))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FNameInput)
                            .addComponent(CityInput, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(StateInput)
                            .addComponent(AL2Input)
                            .addComponent(AL1Input)
                            .addComponent(PhoneInput)
                            .addComponent(EmailInput)
                            .addComponent(LNameInput)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(CreateButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(headingLabel))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FNameLabel)
                    .addComponent(FNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNameLabel)
                    .addComponent(LNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailLabel)
                    .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PhoneLabel)
                    .addComponent(PhoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AL1Label)
                    .addComponent(AL1Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AL2Label)
                    .addComponent(AL2Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StateLabel)
                    .addComponent(StateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CityLabel)
                    .addComponent(CityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(CreateButton)
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
                JPanel panel = new AdminPage();
                currentFrame.dispose();
                JFrame frame = new JFrame("Admin Page");
                frame.add(panel);
                frame.setSize(750,600);
                frame.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        // TODO add your handling code here
        Guest guestDetails = new Guest();
        guestDetails.setFname(FNameInput.getText());
        guestDetails.setLname(LNameInput.getText());
        guestDetails.setEmail(EmailInput.getText());
        guestDetails.setPhone(PhoneInput.getText());
        guestDetails.setAddressLine1(AL1Input.getText());
        guestDetails.setAddressLine2(AL2Input.getText());
        guestDetails.setCity(CityInput.getText());
        guestDetails.setState(StateInput.getText());
        
        Database.createGuest(guestDetails);
        clearForm();
        
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
                JPanel panel = new AdminPage();
                currentFrame.dispose();
                JFrame frame = new JFrame("Admin Page");
                frame.add(panel);
                frame.setSize(750,600);
                frame.setVisible(true);
        
        
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void clearForm(){
        FNameInput.setText("");
        LNameInput.setText("");
        EmailInput.setText("");
        PhoneInput.setText("");
        AL1Input.setText("");
        AL2Input.setText("");
        CityInput.setText("");
        StateInput.setText("");
    }
    private void FNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AL1Input;
    private javax.swing.JLabel AL1Label;
    private javax.swing.JTextField AL2Input;
    private javax.swing.JLabel AL2Label;
    private javax.swing.JTextField CityInput;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JButton CreateButton;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField FNameInput;
    private javax.swing.JLabel FNameLabel;
    private javax.swing.JTextField LNameInput;
    private javax.swing.JLabel LNameLabel;
    private javax.swing.JTextField PhoneInput;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JTextField StateInput;
    private javax.swing.JLabel StateLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel headingLabel;
    // End of variables declaration//GEN-END:variables
}
