/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import model.*;
import controller.*;

/**
 *
 * @author lenovo
 */
public class MainFrame extends javax.swing.JFrame {
    
//    flowControl fc = new flowControl();
    LoginPage lp = new LoginPage();
    
    StaysView stayV = new StaysView();
    DefaultTableModel globalModel = (DefaultTableModel) stayV.staysTable.getModel();
    ArrayList<Stays> staysArray = new ArrayList<> ();
    
    MembershipView membershipV = new MembershipView();
    DefaultTableModel globalModelMembership = (DefaultTableModel) membershipV.membershipTable.getModel();
    
    public ArrayList<Guest> globalArrayList = new ArrayList<>();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        
        String accessVariable = lp.fc.getAccess();
//          String accessVariable = lp.access;
        System.out.println("before variable " + accessVariable);
        if(accessVariable.equals("GRANTED")){
        initComponents();
        }
        else{
//        flowControl fc = new flowControl();
        JFrame frame = new JFrame("Login");
        JPanel panel = new LoginPage();
        frame.add(panel);
        frame.setSize(750, 600);
        frame.setVisible(true);

        MainFrame.this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutButton = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        MembershipLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JSplitPane();
        buttonPanelTOP = new javax.swing.JPanel();
        ProfileButton = new javax.swing.JButton();
        StaysButton = new javax.swing.JButton();
        MembershipsButton = new javax.swing.JButton();
        VouchersButton = new javax.swing.JButton();
        displayPanelBOT = new javax.swing.JPanel();
        searchInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        nameDataLabel = new javax.swing.JLabel();
        phoneDataLabel = new javax.swing.JLabel();
        emailDataLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 600));

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        NameLabel.setText("Name:");

        PhoneLabel.setText("Phone:");

        EmailLabel.setText("Email:");

        MembershipLabel.setText("Membership Tier:");

        mainPanel.setDividerLocation(40);
        mainPanel.setDividerSize(3);
        mainPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        buttonPanelTOP.setBackground(new java.awt.Color(255, 102, 102));

        ProfileButton.setText("Profile");
        ProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButtonActionPerformed(evt);
            }
        });

        StaysButton.setText("Stays");
        StaysButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaysButtonActionPerformed(evt);
            }
        });

        MembershipsButton.setText("Memberships");
        MembershipsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MembershipsButtonActionPerformed(evt);
            }
        });

        VouchersButton.setText("Vouchers");
        VouchersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VouchersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelTOPLayout = new javax.swing.GroupLayout(buttonPanelTOP);
        buttonPanelTOP.setLayout(buttonPanelTOPLayout);
        buttonPanelTOPLayout.setHorizontalGroup(
            buttonPanelTOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelTOPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(StaysButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MembershipsButton)
                .addGap(111, 111, 111)
                .addComponent(VouchersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        buttonPanelTOPLayout.setVerticalGroup(
            buttonPanelTOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelTOPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelTOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfileButton)
                    .addComponent(StaysButton)
                    .addComponent(MembershipsButton)
                    .addComponent(VouchersButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setTopComponent(buttonPanelTOP);

        displayPanelBOT.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout displayPanelBOTLayout = new javax.swing.GroupLayout(displayPanelBOT);
        displayPanelBOT.setLayout(displayPanelBOTLayout);
        displayPanelBOTLayout.setHorizontalGroup(
            displayPanelBOTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        displayPanelBOTLayout.setVerticalGroup(
            displayPanelBOTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mainPanel.setRightComponent(displayPanelBOT);

        jLabel1.setText("Search Guest:");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameDataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MembershipLabel)
                        .addGap(188, 188, 188))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phoneDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailDataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(searchButton))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(MembershipLabel)
                    .addComponent(nameDataLabel))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneLabel)
                    .addComponent(phoneDataLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(emailDataLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MembershipsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MembershipsButtonActionPerformed
        // TODO add your handling code here:
//        MembershipView membershipView = new MembershipView();
        mainPanel.setBottomComponent(membershipV);
        membershipV.repaint();
    }//GEN-LAST:event_MembershipsButtonActionPerformed

    private void VouchersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VouchersButtonActionPerformed
        // TODO add your handling code here:
        VoucherView voucherView = new VoucherView();
        mainPanel.setBottomComponent(voucherView);
    }//GEN-LAST:event_VouchersButtonActionPerformed

    private void ProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileButtonActionPerformed
        // TODO add your handling code here:
        System.out.print("enter");
        ProfileView profileView = new ProfileView();
//        profileView.reset();
        mainPanel.setBottomComponent(profileView);
        profileView.setDetails(globalArrayList);
//        profileView.removeAll();
        profileView.repaint();
    }//GEN-LAST:event_ProfileButtonActionPerformed

    private void StaysButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaysButtonActionPerformed
        // TODO add your handling code here:
//        StaysView staysView = new StaysView();
        mainPanel.setBottomComponent(stayV);
        stayV.repaint();
    }//GEN-LAST:event_StaysButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("LOGGED OUT");
//        new MainFrame().setVisible(false);
//        new LoginPage().setVisible(true);
        JFrame frame = new JFrame("Login");
        JPanel panel = new LoginPage();
        frame.add(panel);
        frame.setSize(750, 600);
        frame.setVisible(true);

        MainFrame.this.dispose();
        
        lp.fc.revokeAccess();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<Guest> guestDetails = new ArrayList<>();
        ArrayList<Stays> stayDetails = new ArrayList<> ();
        ArrayList<Membership> membershipDetails = new ArrayList<> ();
        String searchQuery;
        searchQuery = searchInput.getText();
        
        guestDetails = Database.viewGuest(searchQuery);
        globalArrayList.clear();
        Guest guest = guestDetails.get(0);
        globalArrayList.add(guest);
        nameDataLabel.setText(guest.getFname());
        emailDataLabel.setText(guest.getEmail());
        phoneDataLabel.setText(guest.getPhone());
        MainFrame.this.repaint();
//        ProfileView pf = new ProfileView();
//        pf.reset();
        
        stayDetails = Database.getStays(searchQuery);
//        Stays stay = stayDetails.get(0);
        try {
//            this.users = DatabaseConnector.getAllusers();
//            StaysView stayV = new StaysView();
//            DefaultTableModel model = (DefaultTableModel) stayV.staysTable.getModel();
            globalModel.setRowCount(0);
            for (Stays s : stayDetails) {
                Object[] row = new Object[6];
                row[0] = s.getGuestId();
//                System.out.println(s.getGuestId());
//                row[0] = u;
                row[1] = s.getHotelName();
//                System.out.println(s.getHotelName());
                row[2] = s.getCheckInDate();
                row[3] = s.getCheckOutDate();
                row[4] = s.getPrice();
                row[5] = s.getFeedback();
//                model.addRow(row);
                globalModel.addRow(row);
                
                System.out.println(globalModel);
            }
//            clearFields();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
//        Membership Details
          membershipDetails = Database.getMembership(searchQuery);
//        Stays stay = stayDetails.get(0);
        try {
//            this.users = DatabaseConnector.getAllusers();
//            StaysView stayV = new StaysView();
//            DefaultTableModel model = (DefaultTableModel) stayV.staysTable.getModel();
            globalModelMembership.setRowCount(0);
            for (Membership m : membershipDetails) {
                Object[] row = new Object[6];
                row[0] = m.getMembershipId();
//                System.out.println(s.getGuestId());
//                row[0] = u;
//                System.out.println(s.getHotelName());
                row[1] = m.getGuestEmail();
                row[2] = m.getMembershipTier();
                row[3] = m.getExpiry();
                row[4] = m.getJoin();
                row[5] = m.getType();
//                row[5] = m.getFeedback();
//                model.addRow(row);
                globalModelMembership.addRow(row);
                System.out.println(globalModelMembership);
            }
//            clearFields();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel MembershipLabel;
    private javax.swing.JButton MembershipsButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JButton ProfileButton;
    private javax.swing.JButton StaysButton;
    private javax.swing.JButton VouchersButton;
    private javax.swing.JPanel buttonPanelTOP;
    private javax.swing.JPanel displayPanelBOT;
    private javax.swing.JLabel emailDataLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JSplitPane mainPanel;
    private javax.swing.JLabel nameDataLabel;
    private javax.swing.JLabel phoneDataLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchInput;
    // End of variables declaration//GEN-END:variables
}
