/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import java.util.ArrayList;
import model.*;
/**
 *
 * @author lenovo
 */
public class ProfileView extends javax.swing.JPanel {

    public void reset() {
        FNameDataLabel.setText("");
        LNameDataLabel.setText("");
        emailDataLabel.setText("");
        phoneDataLabel.setText("");
        AL1DataLabel.setText("");
        AL2DataLabel.setText("");
        cityDataLabel.setText("");
        countryDataLabel.setText("");
    }

    /**
     * Creates new form ProfileView
     */
    public ProfileView() {
        initComponents();
    }
    
    public void setDetails(ArrayList<Guest> guest){
        Guest guestDetails = guest.get(0);
        FNameDataLabel.setText(guestDetails.getFname());
        LNameDataLabel.setText(guestDetails.getLname());
        emailDataLabel.setText(guestDetails.getEmail());
        phoneDataLabel.setText(guestDetails.getPhone());
        AL1DataLabel.setText(guestDetails.getAddressLine1());
        AL2DataLabel.setText(guestDetails.getAddressLine2());
        cityDataLabel.setText(guestDetails.getCity());
        countryDataLabel.setText(guestDetails.getState());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FNameLabel = new javax.swing.JLabel();
        LNameLabel1 = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        Phonelabel = new javax.swing.JLabel();
        ALine1Label = new javax.swing.JLabel();
        ALine2Label = new javax.swing.JLabel();
        CityLabel = new javax.swing.JLabel();
        CountryLabel = new javax.swing.JLabel();
        FNameDataLabel = new javax.swing.JLabel();
        LNameDataLabel = new javax.swing.JLabel();
        emailDataLabel = new javax.swing.JLabel();
        phoneDataLabel = new javax.swing.JLabel();
        AL1DataLabel = new javax.swing.JLabel();
        AL2DataLabel = new javax.swing.JLabel();
        cityDataLabel = new javax.swing.JLabel();
        countryDataLabel = new javax.swing.JLabel();

        FNameLabel.setText("First Name:");

        LNameLabel1.setText("Last Name:");

        EmailLabel.setText("Email:");

        Phonelabel.setText("Phone:");

        ALine1Label.setText("Address Line 1:");

        ALine2Label.setText("Address Line 2:");

        CityLabel.setText("City:");

        CountryLabel.setText("Country:");

        emailDataLabel.setText("emailDataLabel");

        phoneDataLabel.setText("PhoneDataLabel");

        AL1DataLabel.setText("Address Label 1");

        AL2DataLabel.setText("PhoneDataLabel");

        cityDataLabel.setText("PhoneDataLabel");

        countryDataLabel.setText("PhoneDataLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FNameDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LNameLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LNameDataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailLabel)
                            .addComponent(Phonelabel))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneDataLabel)
                            .addComponent(emailDataLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ALine1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AL1DataLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(CountryLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(countryDataLabel))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(CityLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cityDataLabel))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(ALine2Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(AL2DataLabel))))
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FNameLabel)
                    .addComponent(ALine1Label)
                    .addComponent(FNameDataLabel)
                    .addComponent(AL1DataLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNameLabel1)
                    .addComponent(ALine2Label)
                    .addComponent(LNameDataLabel)
                    .addComponent(AL2DataLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(CityLabel)
                    .addComponent(emailDataLabel)
                    .addComponent(cityDataLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Phonelabel)
                    .addComponent(CountryLabel)
                    .addComponent(phoneDataLabel)
                    .addComponent(countryDataLabel))
                .addContainerGap(393, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel AL1DataLabel;
    public javax.swing.JLabel AL2DataLabel;
    private javax.swing.JLabel ALine1Label;
    private javax.swing.JLabel ALine2Label;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JLabel CountryLabel;
    private javax.swing.JLabel EmailLabel;
    public javax.swing.JLabel FNameDataLabel;
    private javax.swing.JLabel FNameLabel;
    public javax.swing.JLabel LNameDataLabel;
    private javax.swing.JLabel LNameLabel1;
    private javax.swing.JLabel Phonelabel;
    public javax.swing.JLabel cityDataLabel;
    public javax.swing.JLabel countryDataLabel;
    public javax.swing.JLabel emailDataLabel;
    public javax.swing.JLabel phoneDataLabel;
    // End of variables declaration//GEN-END:variables
}
